theme: jekyll-theme-minimal
title: Siobhan Fitzgerald-Gibson
description: Hello! I’m a technical writer, editor and content strategist. I can help you with your team’s documentation and technical content.
logo: /assets/img/logo-blue.png
