theme: jekyll-theme-minimal
title: Siobhan Fitzgerald-Gibson
description: I’m a technical writer, editor and content strategist with over a decade of experience. I can help you with your team’s documentation and technical content.

